FROM python

ARG PROXY="http://web-proxy.ap.softwaregrp.net:8080"

ENV HTTP_PROXY $PROXY
ENV HTTPS_PROXY $PROXY
ENV http_proxy $PROXY
ENV https_proxy $PROXY

ENV DEBIAN_FRONTEND=noninteractive

RUN mkdir -p /etc/apt && touch /etc/apt/apt.conf \
    && echo "Acquire::http::proxy \"$PROXY\";" > /etc/apt/apt.conf \ 
    && echo "Acquire::https::proxy \"$PROXY\";" >> /etc/apt/apt.conf \ 
    && apt-get update && apt-get install -y sudo jq

# Download terraform
ARG TF_VERSION="0.12.29"
RUN curl -o tf.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip && unzip tf.zip -d /usr/bin/ && rm -fr tf.zip

# User to run container
ARG USER_ID
ARG GROUP_ID
ARG DEV_USER=hacker
RUN if [ ${USER_ID:-0} -ne 0 ] && [ ${GROUP_ID:-0} -ne 0 ]; then \
    groupadd -g ${GROUP_ID} ${DEV_USER} &&\
    useradd -m -l -u ${USER_ID} -g ${DEV_USER} ${DEV_USER}  &&\
    usermod --shell /bin/bash ${DEV_USER} &&\
    usermod -a -G root ${DEV_USER} &&\
    echo "${DEV_USER}:${DEV_USER}" |  chpasswd &&\
    echo 'export PS1="\u@ \[\e[32m\]\w\[\e[m\]\[\e[35m\]\[\e[m\]\\n$ "' \
        >> /home/${DEV_USER}/.bashrc &&\
    echo $DEV_USER ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$DEV_USER  &&\
    chmod 0440 /etc/sudoers.d/$DEV_USER  \
;fi
USER ${DEV_USER}
WORKDIR /home/${DEV_USER}

# Install python packages
COPY ./requirements*.txt /
ENV PATH=/home/${DEV_USER}/.local/bin:$PATH
RUN pip install -U --no-cache-dir -r /requirements-dev.txt &&\
    pip install -U --upgrade pip

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=

# Keep container live
CMD tail -f /dev/null

